version: "3"
services:
  identicon:
    image: "neumaticvmax/digi-node:1.0"
    environment:
      - ENV=DEV
    volumes:
      - /digi/appz/identicon:/app
    ports:
      - "3000:3000"
    links:
      - dnmonster
      - redis

  dnmonster:
    image: "amouat/dnmonster:1.0"

  redis:
    image: "redis:4.0"
